---
version: 2.1
jobs:
  build:
    working_directory: ~/judge
    docker:
      - image: cimg/ruby:2.7
        environment:
          RAILS_ENV: test
      - image: keinos/sqlite3:3.40.1

    steps:
      - checkout

      - run: bundle install
      - run: bundle exec appraisal install

      - run: bundle install
      - run: bundle exec appraisal install

      - run: bundle exec appraisal rspec


      - run: bundle exec appraisal rspec
