---
version: 2
jobs:
  build:
    working_directory: ~/judge
    docker:
      - image: circleci/ruby:2.4.1
        environment:
          PGHOST: localhost
          PGUSER: judge
          RAILS_ENV: test
      - image: postgres:9.5
        environment:
          POSTGRES_USER: judge
          POSTGRES_DB: judge_test
          POSTGRES_PASSWORD: ""
    steps:
        - checkout

      # Setup the environment
      - run: cp .sample.env .env

      # Setup the database
      - run: bundle exec rake db:setup

      # Run the tests
      - run: bundle exec rake